// <auto-generated />
namespace Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NameTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201505201209261_NameTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
